### PR TITLE
Extract pngs from vhstack.svg

### PR DESCRIPTION
**Pull request by bencooper222**
Used https://www.jujens.eu/posts/en/2017/Feb/13/extract-images-svg/ to pull out the pngs so ImgBot can now optimize them. We'll see how much that helps.

### CODE REVIEW

**Comment by bencooper222** [comment]
- [x] remove the python script I accidentally committed.

**Comment by bencooper222** [comment]
Note that making 9 img requests in prod is a bad bad idea. It's probably best to optimize the images and then roll them back inline the svg.

**Comment by cktang88** [comment]
this really doesn't solve the problem

**Comment by bencooper222** [comment]
It's about a 33% reduction - certainly not a fully solved problem though.

**Comment by bencooper222** [comment]
It hasn't propagated to Heroku yet (I guess continuous deploy is disabled?) but I think this should be a huge improvement. I think it's actually a 67% reduction.

**Pull request merged**
